CREATE TABLE IF NOT EXISTS empresas (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cnpj INT UNSIGNED,
    cidade_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (cnpj)
)